{
  "type": "record",
  "name": "Coursier",
  "namespace": "model",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "first_name",
      "type": "string",
      "default": "undefined"
    },
    {
      "name": "position",
      "type": {
        "type": "record",
        "name": "Position",
        "namespace": "model",
        "fields": [
          {
            "name": "latitude",
            "type": "double"
          },
          {
            "name": "longitude",
            "type": "double"
          }
        ]
      }
    }
  ]
}