// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace model
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
	public partial class Coursier : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Coursier"",""namespace"":""model"",""fields"":[{""name"":""id"",""type"":""long""},{""name"":""first_name"",""default"":""undefined"",""type"":""string""},{""name"":""position"",""type"":{""type"":""record"",""name"":""Position"",""namespace"":""model"",""fields"":[{""name"":""latitude"",""type"":""double""},{""name"":""longitude"",""type"":""double""}]}}]}");
		private long _id;
		private string _first_name;
		private model.Position _position;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Coursier._SCHEMA;
			}
		}
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				this._first_name = value;
			}
		}
		public model.Position position
		{
			get
			{
				return this._position;
			}
			set
			{
				this._position = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.first_name;
			case 2: return this.position;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.Int64)fieldValue; break;
			case 1: this.first_name = (System.String)fieldValue; break;
			case 2: this.position = (model.Position)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
